### ISSUE TITLE
[Feature Request] Use partial/custom prompt after "end at this step"

### ISSUE THREAD

**Issue by catboxanon** [opparco/stable-diffusion-webui-two-shot#22]
Just an idea. Currently, when the `end at this step` option is used, it then uses the prompt as-is, with all parts of composable diffusion. In my experience this essentially overbakes the output due to stacking several ANDs and isn't very useful, so I'm forced to leave this option equal to the amount of steps used to get something that looks nice. My thought is, could we specify a subprompt index or a custom prompt to use once the end at step is reached, where composable diffusion is no longer used? This would allow this extension to guide the initial denoising process, and then the vanilla denoising process can take over to handle the rest, without overbaking the final result.

The motivation for this would be that I believe this should hopefully increase image quality further, while also making processing less intensive. I thought this may have been possible via [prompt editing](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#prompt-editing) as well, but that seems to be incompatible with composable diffusion (or at least with this extension). Please correct me if I'm wrong.

I haven't dug into the code yet but I may take a crack at this. Opening this issue incase someone else does or if they want to give any more insight.

**Comment by Xyem** [comment]
I actually expected it to only use the first subprompt once it the Latent Couple stopped.. surprised to hear this isn't the case, as I have gotten some really nice images from ending the Latent Couple either side of halfway.

**Comment by catboxanon** [comment]
Closing as stale.
