### ISSUE TITLE
Breaks the css in the Extra Networks tab

### ISSUE THREAD

**Issue by NoppaiKohai** [opparco/stable-diffusion-webui-two-shot#37]
If you have your LORA / Checkpoints etc set up in subfolders to group them, adding this extension breaks the CSS in the Extra Networks Tab

This is what it looks like without the extension

![image](https://user-images.githubusercontent.com/7308004/226709817-24d05c4f-6e8a-434a-8c2c-8530d5777b07.png)

while this is what it looks like as soon as you add the extension

![image](https://user-images.githubusercontent.com/7308004/226709920-d816a862-68c4-48fe-abd6-1529e3b948e7.png)

This makes the extra network nearly unusable when you have a lot of files, because the navigation bar to swap between your subfolders gets pushed way down. For example, if I click LORA without filtering it by Meme, it shows ALL my Lora's and the subfolder navigation bar is like 5 screen heights down the page and I have to scroll all the way down just to filter back to the category I actually wanted to see

**Comment by ColorfanXP** [comment]
Try checking out the the fork. If you look on the extensions tab in auto1111, there seems to be a new maintainer.

**Comment by NoppaiKohai** [comment]
That's the one I'm using, but there's no way to report an issue there that I can tell

**Comment by NoppaiKohai** [comment]
Resolved, this branch fixes the issue https://github.com/SoCuteShibe/stable-diffusion-webui-two-shot
