### ISSUE TITLE
If you click apply after selecting in visualize, an error occurs

### ISSUE THREAD

**Issue by kakaruYH03** [opparco/stable-diffusion-webui-two-shot#5]
<img width="929" alt="화면 캡처 2023-02-14 184546" src="https://user-images.githubusercontent.com/54255373/218699961-091f37db-dc63-4f29-9fdf-ccc3e9b860cc.png">

<img width="850" alt="화면 캡처 2023-02-14 184559" src="https://user-images.githubusercontent.com/54255373/218699974-087fb8d4-bedd-4e1d-a673-455ccb283f90.png">

<img width="859" alt="화면 캡처 2023-02-14 184633" src="https://user-images.githubusercontent.com/54255373/218700075-682ab788-5cc5-472b-b4be-b133e9a7fc26.png">

An update failure error occurs when git apply --ignore-whitespace extensions/stable-diffusion-webui-two-shot/cfg_denoised_callback-ea9bd9fc.patch is entered

**Comment by opparco** [comment]
the commit 5b0ac8d9e16972876bb62d1d12c68d7164344507 solved the issue.
